// Plain-language glossary. Every definition is one sentence at a grade-9 reading
// level with NO hard words nested inside (the #1 red-team finding: terms used
// before they are defined). Keys are lowercase; <Define> matches case-insensitively.

export interface GlossEntry {
  term: string
  def: string
}

export const GLOSSARY: Record<string, GlossEntry> = {
  // ---- Shared developmental + mechanics terms (used across acts) ----
  ectoderm: { term: 'ectoderm', def: 'The outer layer of the early embryo; it makes skin and nervous tissue, and the neural crest comes from its edge.' },
  mesoderm: { term: 'mesoderm', def: 'The middle layer of the early embryo; it makes muscle, bone, blood, and the heart.' },
  endoderm: { term: 'endoderm', def: 'The inner layer of the early embryo; it makes the lining of the gut and lungs.' },
  gastrulation: { term: 'gastrulation', def: 'The early step where the ball of cells folds and sorts into three layers (ectoderm, mesoderm, endoderm).' },
  'neural tube': { term: 'neural tube', def: 'The early tube of cells that becomes the brain and spinal cord; the neural crest pinches off from its top edge.' },
  mesenchyme: { term: 'mesenchyme', def: 'Loose, unsettled cells in a watery matrix that can crawl and later become bone, cartilage, or connective tissue.' },
  multipotent: { term: 'multipotent', def: 'Able to become several different cell types, but not every type.' },
  tripotent: { term: 'tripotent', def: 'A narrower case of multipotent: able to become one of three types (here bone, dermis, or cartilage).' },
  haptotaxis: { term: 'haptotaxis', def: 'When a cell crawls by following a trail of stickiness in the matrix, moving toward where it grips best.' },
  integrin: { term: 'integrin', def: "A receptor that reaches through the cell's surface and grips the matrix outside, bolting the inside of the cell to the outside." },
  'focal adhesion': { term: 'focal adhesion', def: "A cluster of integrins that forms a strong anchor linking the matrix outside to the cell's skeleton inside." },
  actomyosin: { term: 'actomyosin', def: "The cell's muscle-like team of actin filaments and myosin motors that pull and create tension." },
  contractility: { term: 'contractility', def: 'A cell’s ability to pull on itself and its surroundings using its actin and myosin.' },
  'phospho-mlc': { term: 'phospho-MLC', def: 'A tagged (phosphorylated) form of myosin light chain; it is the on-switch that lets the cell pull, so finding it marks where the cell is actively contracting.' },
  mechanotransduction: { term: 'mechanotransduction', def: 'Turning a physical force, like stiffness or pulling, into a chemical signal the cell’s genes can read.' },
  mechanosensor: { term: 'mechanosensor', def: 'A part that senses physical force and passes the message along, like a tiny force gauge.' },
  tead: { term: 'TEAD', def: 'A DNA-gripping partner that YAP and TAZ team up with in the nucleus to switch target genes on.' },
  'beta-catenin': { term: 'beta-catenin', def: 'The inside-the-cell messenger that carries the Wnt signal to the nucleus to switch on the bone program.' },
  wnt: { term: 'Wnt', def: 'A signal one group of cells releases to change nearby cells; here it flips the switch toward bone.' },
  osterix: { term: 'Osterix', def: 'A bone gene that RUNX2 switches on next, carrying the bone-building program further.' },
  'extracellular matrix': { term: 'extracellular matrix', def: 'The web of proteins outside cells that they live on, grip, and pull against.' },
  collagen: { term: 'collagen', def: 'The most common rope-like protein in the matrix; how tightly it is tied sets how stiff a tissue feels.' },
  'in-vivo': { term: 'in-vivo', def: 'Inside a living body, as opposed to in a dish or a model.' },
  deterministic: { term: 'deterministic', def: 'Following a fixed rule, so the same inputs always give the same result.' },
  ctgf: { term: 'CTGF', def: 'A gene that YAP and TAZ switch on when they are active in the nucleus; used as a sign the switch is on.' },
  cyr61: { term: 'CYR61', def: 'Another gene YAP and TAZ switch on when active; like CTGF, it marks that the switch is on.' },
  osteoblast: { term: 'osteoblast', def: 'A bone-building cell.' },
  'intramembranous ossification': { term: 'intramembranous ossification', def: 'Building bone directly from mesenchyme cells, without a cartilage model first; this is how the flat skull bones form.' },
  delamination: { term: 'delamination', def: 'When a cell loosens from a sheet of connected cells and leaves to crawl on its own.' },
  differentiation: { term: 'differentiation', def: 'When a cell becomes specialized by turning certain genes on and others off, so it takes on one job such as bone, dermis, or cartilage.' },
  // ---- Act III "Derail" terms ----
  lox: {
    term: 'LOX',
    def: 'An enzyme (lysyl oxidase) that ties collagen fibers together, making the matrix denser and stiffer.',
  },
  durotaxis: {
    term: 'durotaxis',
    def: 'When cells crawl toward stiffer surroundings, following a stiffness trail like a path uphill.',
  },
  'basement membrane': {
    term: 'basement membrane',
    def: 'A thin, dense sheet that normally walls off a tissue; cancer cells break through it during local invasion.',
  },
  mmp: {
    term: 'MMP',
    def: 'Enzymes that work like scissors, cutting the matrix and the basement membrane to open a path.',
  },
  emt: {
    term: 'EMT',
    def: 'A change where a settled, connected cell becomes looser and more mobile; it helps a cell invade but is not the same as spreading to other organs.',
  },
  metastasis: {
    term: 'metastasis',
    def: 'When cancer cells spread from where they started to distant parts of the body, which is different from local invasion at the margin.',
  },
  'local invasion': {
    term: 'local invasion',
    def: 'When cells cross the basement membrane into the nearby tissue; this is not the same as spreading to distant organs.',
  },
  stroma: {
    term: 'stroma',
    def: 'The supportive tissue and matrix around cells, where an invading cell pushes in.',
  },
  // ---- Act II "Differentiate" terms ----
  yap: {
    term: 'YAP',
    def: 'A protein that carries a physical signal, like how stiff the surroundings are, to the genes; when it moves into the nucleus it helps switch certain genes on.',
  },
  taz: {
    term: 'TAZ',
    def: 'A partner protein to YAP that does the same job; the two are usually named together as YAP and TAZ.',
  },
  runx2: {
    term: 'RUNX2',
    def: 'A master gene switch that tells a cell to start becoming bone.',
  },
  sox9: {
    term: 'Sox9',
    def: 'A master gene switch for cartilage; it is the setting a cell falls back to by default.',
  },
  bone: {
    term: 'bone',
    def: 'The hard tissue that makes up the skeleton, including the front of the skull.',
  },
  cartilage: {
    term: 'cartilage',
    def: 'The smooth, bendy tissue like the tip of your nose or your ears; it is the default a crest cell starts from before bone is chosen.',
  },
  'substrate stiffness': {
    term: 'substrate stiffness',
    def: 'How hard or soft the surface under a cell is, from soft like fat up to firm like forming bone.',
  },
  model: {
    term: 'model',
    def: 'A simplified stand-in you can change and study, used instead of the real living tissue.',
  },
  'nuclear localization': {
    term: 'nuclear localization',
    def: 'Whether a protein is sitting inside the nucleus, where the genes are, or outside it in the cytoplasm.',
  },
  replicate: {
    term: 'replicate',
    def: 'One independent repeat of the whole experiment: the same everyday idea as a trial (one coin flip) or a sample (one student in a poll). It is the unit you count, so your sample size n is the number of replicates, not the pieces inside them. In this lab one replicate is one embryo (Develop), one model run (Differentiate), or one sample region (Derail).',
  },
  replicates: {
    term: 'replicates',
    def: 'The independent repeats of your experiment (your trials or samples). Counting more replicates, never more cells inside one, is what makes a result trustworthy.',
  },
  trial: {
    term: 'trial',
    def: 'One independent repeat of a test, like a single coin flip. In this lab, one replicate is one trial. Repeating the trial is both a statistics step (it grows your real n) and a bias check (it shows whether a result was real or just how you did it once).',
  },
  bias: {
    term: 'bias',
    def: 'A hidden tilt that pushes a result one way without you meaning it to: expecting an answer and unconsciously drawing a boundary, or picking a field of view, in the way that fits. It is not cheating, and every scientist has it. Repeating a trial blind, and in other hands, is how you catch it.',
  },
  blind: {
    term: 'blind',
    def: 'Making the call before you can see the answer, so your expectations cannot steer it. For example, drawing the cell boundaries without knowing which group a sample is in. Blinding is a guard against bias.',
  },
  'sample size': {
    term: 'sample size (n)',
    def: 'How many independent replicates (trials) you have, written n. n is the number of replicates, never the number of cells inside them; more replicates make the result more trustworthy.',
  },
  run: {
    term: 'run',
    def: 'One time you carry the experiment all the way through. On the model bench (Differentiate), each model run is one replicate, one independent trial at a setting. The "Run / Measure" step is the stage where you carry out the experiment and take a reading; "your run" on the final screen means your whole trip through the loop.',
  },
  abstract: {
    term: 'abstract',
    def: 'A short summary of the whole report (about 150 to 300 words) that answers what you did, why, how, what you found, and what it means. Scientists write it last, because it summarizes everything else.',
  },
  imrad: {
    term: 'IMRaD',
    def: 'The standard shape of a science paper: Introduction, Methods, Results, and Discussion.',
  },
  conclusion: {
    term: 'conclusion',
    def: 'The part where you say what your results mean, not just what they were: you interpret the data, state what you can claim and how sure you are, and name what you still cannot say.',
  },
  revision: {
    term: 'revision',
    def: 'Going back to improve a draft: cutting extra words, fixing unclear sentences, and checking that every claim is backed by evidence.',
  },
  concision: {
    term: 'concision',
    def: 'Saying it in as few words as the meaning needs, so the reader is not slowed down.',
  },
  'neural crest cells': {
    term: 'neural crest cells',
    def: 'Special cells that travel through the early embryo and build parts of the face and skull.',
  },
  'frontal bone': {
    term: 'frontal bone',
    def: 'The bone of the forehead, at the front of the skull.',
  },
  cleft: {
    term: 'cleft',
    def: 'A split or gap left when two parts of the face grow toward each other but do not fully join (fuse) before birth.',
  },
  palate: {
    term: 'palate',
    def: 'The roof of the mouth.',
  },
  mechanism: {
    term: 'mechanism',
    def: 'The step-by-step way something actually works.',
  },
  claim: {
    term: 'claim',
    def: 'The one sentence supported by your evidence.',
  },
  pi: {
    term: 'PI',
    def: 'The principal investigator: the scientist who runs the lab (your boss).',
  },
  'z-axis': {
    term: 'z-axis',
    def: 'The depth direction (toward you and away). A flat photo has no z-axis.',
  },
  fn1: {
    term: 'FN1',
    def: 'A protein (fibronectin) that cells crawl along like a road as they move.',
  },
  fibronectin: {
    term: 'fibronectin (FN1)',
    def: 'A protein that cells crawl along like a road as they move.',
  },
  graded: {
    term: 'graded',
    def: 'Low on one side and high on the other, like a ramp.',
  },
  ecm: {
    term: 'ECM',
    def: 'The "extracellular matrix": the scaffold of material outside cells that they sit on and crawl through.',
  },
  nucleus: {
    term: 'nucleus',
    def: 'The control center at the middle of a cell. Here we use it as a dot to mark where each cell is.',
  },
  nuclei: {
    term: 'nuclei',
    def: 'More than one nucleus (the center of a cell), used here as dots marking where cells are.',
  },
  'nuclear spacing': {
    term: 'nuclear spacing',
    def: 'How far apart the cell centers (the dots) sit from each other.',
  },
  'non-randomly spaced': {
    term: 'non-randomly spaced',
    def: 'Sitting in a pattern with even gaps, instead of scattered or clumped by chance.',
  },
  hypothesis: {
    term: 'hypothesis',
    def: 'Your best guess for HOW something works, written so an experiment could prove it wrong.',
  },
  falsifiable: {
    term: 'falsifiable',
    def: 'Able to be proven wrong by a real measurement. Good science questions are falsifiable.',
  },
  control: {
    term: 'control group',
    def: 'A second group you set up to compare against, so you can tell if your change actually did anything.',
  },
  'control group': {
    term: 'control group',
    def: 'A second group you set up to compare against, so you can tell if your change actually did anything.',
  },
  'biological replicate': {
    term: 'biological replicate',
    def: 'A replicate that is a whole living thing, here a different embryo, not just another cell from the same one. It is one independent trial of the experiment.',
  },
  micrograph: {
    term: 'micrograph',
    def: 'A photo taken through a microscope.',
  },
  cellpose: {
    term: 'Cellpose',
    def: 'A computer tool that finds each cell in a microscope photo and marks its center.',
  },
  segment: {
    term: 'segment',
    def: 'To have the computer find each cell and mark its center.',
  },
  segmentation: {
    term: 'segmentation',
    def: 'Having the computer find each cell in an image and mark its center.',
  },
  centroid: {
    term: 'centroid',
    def: 'The exact center point of a cell.',
  },
  voronoi: {
    term: 'Voronoi',
    def: 'A way of drawing a "territory" around each cell, so you can see how packed or spread out they are.',
  },
  'nearest-neighbor': {
    term: 'nearest-neighbor distance',
    def: 'How far each cell is from the closest other cell.',
  },
  µm: {
    term: 'µm (micron)',
    def: 'A tiny unit of length. One micron is a millionth of a meter, about the size of a small cell part.',
  },
  '2d-projected': {
    term: '2D-projected distance',
    def: 'A distance measured on a flat photo, which is only a shadow of the real 3D distance.',
  },
  'claim ceiling': {
    term: 'claim ceiling',
    def: 'The strongest thing your tools let you honestly say. You cannot claim more than your best evidence supports.',
  },
  'p-value': {
    term: 'p-value',
    def: 'How likely your result is just luck. A smaller p-value means luck is a less likely explanation.',
  },
  pseudoreplication: {
    term: 'pseudoreplication',
    def: 'Counting many cells from a few animals as if each cell were its own experiment. It fakes a big sample size.',
  },
  afm: {
    term: 'AFM',
    def: 'A machine that presses a tiny tip on tissue to measure how stiff it is. It usually needs dead tissue.',
  },
  fret: {
    term: 'FRET',
    def: 'A method using special glowing tags to sense the pulling force between molecules.',
  },
  brillouin: {
    term: 'Brillouin',
    def: 'A light-based method for measuring how stiff a tissue is.',
  },
  'magnetic actuation': {
    term: 'magnetic actuation',
    def: 'Using tiny magnetic beads and magnets to push on tissue and measure how it pushes back.',
  },
  tension: {
    term: 'tension',
    def: 'The pulling force between cells or molecules. You cannot see it by looking at where cells sit.',
  },
  'mol*': {
    term: 'Mol*',
    def: 'A free tool for viewing the 3D shape of a protein.',
  },
  alphafold: {
    term: 'AlphaFold',
    def: 'An AI that predicts the 3D shape of a protein. The shapes are good guesses, not photos.',
  },

  // --- vocabulary defs added 2026-06-29 so every chapter chip is tappable ---
  ["2d culture"]: { term: "2D culture", def: "Growing cells on a flat surface like the bottom of a dish, where they spread out wide but do not have the 3D surroundings they would feel inside a real body." },
  ["3d culture"]: { term: "3D culture", def: "Growing cells inside a soft, jelly-like material so they are surrounded on all sides, which is closer to how cells really live inside the body than growing them flat in a dish." },
  ["actin"]: { term: "actin", def: "A protein inside the cell that links together into long fibers, building the internal framework the cell uses to hold its shape and pull on things." },
  ["actin cytoskeleton"]: { term: "actin cytoskeleton", def: "The web of actin fibers inside a cell that acts like its skeleton and muscles, giving the cell shape and letting it grip and pull on the matrix outside." },
  ["actin filament"]: { term: "actin filament", def: "One long thread made of many actin proteins joined end to end, used as a cable the cell can pull on to generate force." },
  ["actomyosin tension"]: { term: "actomyosin tension", def: "The pulling force a cell makes when its motor protein myosin tugs on actin cables, the force that gets passed to the matrix and that sends YAP and TAZ into the nucleus to flip a cell's fate." },
  ["adhesion area"]: { term: "adhesion area", def: "How much surface a cell uses to stick to the matrix beneath it, where a larger gripping area usually means the cell can build up more pulling force." },
  ["afm (atomic force microscopy)"]: { term: "AFM (atomic force microscopy)", def: "A tool that presses a tiny tip into a sample to directly measure how stiff or soft it is, and in this lab it sits at the top of the Measurement Ladder as a locked rung you do not actually have." },
  ["atomic force microscopy"]: { term: "atomic force microscopy", def: "A tool that presses a very small tip into a sample to directly measure its stiffness or the force on it, treated in this lab as a locked top-rung tool whose claims stay out of reach." },
  ["atomic force microscopy (afm)"]: { term: "atomic force microscopy (AFM)", def: "A tool that pushes a tiny tip into a sample to measure stiffness or force directly, and in this lab it is a locked rung at the top of the Measurement Ladder that you cannot claim from." },
  ["balance of remodeling"]: { term: "balance of remodeling", def: "The steady give-and-take of cells building up and breaking down the matrix around them, where healthy tissue keeps the two roughly even instead of letting one side take over." },
  ["basement membrane (bm)"]: { term: "basement membrane (BM)", def: "A thin, sheet-like layer of matrix that normal tissues sit on and stay behind, a boundary that an invading cancer cell must breach to spread." },
  ["blastocyst"]: { term: "blastocyst", def: "An early ball of cells a few days after a fertilized egg starts dividing, hollow inside with an outer shell and an inner cluster that will become the body." },
  ["blastula"]: { term: "blastula", def: "An early stage of an embryo shaped like a hollow ball of cells surrounding a fluid-filled space, formed soon after the egg begins dividing." },
  ["bmp"]: { term: "BMP", def: "A signaling protein cells release to tell nearby cells what to become, including signals that help push cells toward building bone." },
  ["body axes"]: { term: "body axes", def: "The main directions an embryo sets up early on, like head-to-tail and front-to-back, which act as a map telling each part of the body where it belongs." },
  ["breach"]: { term: "breach", def: "When a cell breaks through a barrier it is supposed to stay behind, such as a cancer cell punching through the basement membrane to invade nearby tissue." },
  ["brillouin microscopy"]: { term: "Brillouin microscopy", def: "A way of measuring how stiff a tissue is by shining light into it, without cutting or touching the sample." },
  ["c3a"]: { term: "C3a", def: "A small signaling molecule made by the immune system that can call other cells toward it, acting like a chemical breadcrumb trail." },
  ["cadherin"]: { term: "cadherin", def: "A sticky protein on a cell's surface that links to the same protein on a neighboring cell, holding cells together like Velcro between two cells." },
  ["carcinoma"]: { term: "carcinoma", def: "A cancer that starts in the lining or covering cells of the body, such as the breast carcinoma in this case that stiffens its own matrix and invades." },
  ["causal question"]: { term: "causal question", def: "A question that asks whether one thing actually makes another thing happen, not just whether the two appear together." },
  ["ceiling"]: { term: "ceiling", def: "The highest claim your evidence allows, set by your most direct tool: you may only claim as high as that tool actually reached, never higher." },
  ["cell adhesion"]: { term: "cell adhesion", def: "The way a cell sticks to the matrix around it or to other cells, the grip that lets it hold its place, sense its surroundings, and pull." },
  ["cell cycle"]: { term: "cell cycle", def: "The repeating set of steps a cell goes through to grow, copy its DNA, and split into two new cells." },
  ["cell fate"]: { term: "cell fate", def: "What a cell ends up becoming, such as a bone cell or a cartilage cell, once it commits to one job." },
  ["cell fate decision"]: { term: "cell fate decision", def: "The moment a cell commits to one type over another, like choosing the bone path (RUNX2) instead of the cartilage path (Sox9) based on signals it senses." },
  ["cell junctions"]: { term: "cell junctions", def: "The connection points that hold neighboring cells together and link them up, letting a group of cells act as one connected sheet or tissue." },
  ["cell spread"]: { term: "cell spread", def: "How wide and flat a cell stretches out on a surface, where a more spread-out shape usually goes along with stronger pulling and more YAP and TAZ in the nucleus." },
  ["cell-cell adhesion"]: { term: "cell-cell adhesion", def: "The sticking of one cell directly to another, often through cadherin proteins, that keeps cells joined in a group instead of drifting apart." },
  ["chemotaxis"]: { term: "chemotaxis", def: "When a cell moves toward or away from a chemical signal, following the trail to wherever the signal is strongest or weakest." },
  ["claim licensing"]: { term: "claim licensing", def: "The rule that each rung of the Measurement Ladder only earns you certain claims, so the tool you used decides what you are allowed to say." },
  ["cleavage"]: { term: "cleavage", def: "The rapid early cell divisions right after an egg is fertilized, splitting it into many smaller cells without the whole thing getting bigger." },
  ["cleft lip and palate"]: { term: "cleft lip and palate", def: "A birth difference where the parts of the face that should join together do not fully fuse, leaving a gap in the lip and the roof of the mouth, as in Baby Mateo's case." },
  ["clutch engagement"]: { term: "clutch engagement", def: "When a cell's grip on the matrix locks in tightly enough that its inner pulling actually transmits force outward, like a car clutch catching so the engine moves the wheels." },
  ["co-attraction"]: { term: "co-attraction", def: "When cells in a group release a signal that pulls their own kind back toward each other, helping a migrating crowd stay together instead of scattering." },
  ["collective migration"]: { term: "collective migration", def: "When a group of cells moves together as a connected team rather than one by one, the way cranial neural crest cells travel to build the frontal bone." },
  ["confinement"]: { term: "confinement", def: "When cells are packed into a tight or narrow space that limits how much room they have to spread and move." },
  ["congestion"]: { term: "congestion", def: "When too many cells crowd into one area and get jammed together, leaving little room for them to space out or move freely." },
  ["contact inhibition of locomotion"]: { term: "contact inhibition of locomotion", def: "A rule cells follow where two moving cells that bump into each other stop, change direction, and crawl away, which helps the neural crest cells spread out evenly instead of piling up." },
  ["context"]: { term: "context", def: "The surroundings and conditions a cell is in (like how stiff its matrix is, what shape it has, and what signals reach it), which can change how the cell reads the same instructions." },
  ["context-dependent"]: { term: "context-dependent", def: "When the result of something depends on the situation around it, so the same signal can lead to different outcomes depending on the cell's surroundings." },
  ["contraction"]: { term: "contraction", def: "When a cell's internal actin-and-myosin motors pull and tighten, generating the tension that tugs on the matrix and can send YAP and TAZ into the nucleus." },
  ["control vs mutant"]: { term: "control vs mutant", def: "A comparison where the control is the normal, unchanged version and the mutant has one specific change, so any difference between them points to what that one change does." },
  ["correlation vs causation"]: { term: "correlation vs causation", def: "Correlation means two things tend to happen together, while causation means one actually makes the other happen, and seeing them together does not prove one caused the other." },
  ["covalent bond"]: { term: "covalent bond", def: "A strong chemical link where two atoms share electrons, the kind of tough bond LOX uses to lock matrix fibers together when it stiffens tissue." },
  ["cranial neural crest"]: { term: "cranial neural crest", def: "A group of cells in the head region of the early embryo that travel to new places and build many face and skull structures, including the frontal bone in this sim." },
  ["cranial neural crest cell"]: { term: "cranial neural crest cell", def: "One of the migrating head-region embryo cells that crawls along a fibronectin road and helps build facial bones like the frontal bone." },
  ["cranial neural crest cells"]: { term: "cranial neural crest cells", def: "The migrating head-region embryo cells that crawl along a graded fibronectin road and space themselves out to build the frontal bone." },
  ["cranial neural crest cells (cnccs)"]: { term: "cranial neural crest cells (CNCCs)", def: "The migrating head-region embryo cells (CNCCs for short) that crawl along a graded fibronectin road and space themselves out to build the frontal bone." },
  ["craniofacial mesenchyme"]: { term: "craniofacial mesenchyme", def: "The loose, unspecialized cells in the developing head and face that can become bone or cartilage and form the raw material for face and skull structures." },
  ["crosslink"]: { term: "crosslink", def: "A chemical bridge that ties matrix fibers together; the more crosslinks, the stiffer and tougher the matrix becomes." },
  ["crosslinking"]: { term: "crosslinking", def: "The act of adding chemical bridges between matrix fibers, which is how the LOX enzyme stiffens tissue so a tumor can crawl up its own stiffness gradient." },
  ["ctgf (ccn2)"]: { term: "CTGF (CCN2)", def: "A gene that YAP and TAZ switch on when a cell feels tension, often used as a readout that the grip-pull-signal chain is active." },
  ["cyr61 (ccn1)"]: { term: "CYR61 (CCN1)", def: "Another gene that YAP and TAZ turn on under tension, used like a flag showing the cell is feeling and responding to mechanical force." },
  ["cytoplasm"]: { term: "cytoplasm", def: "The jelly-like fluid filling a cell outside the nucleus, where YAP and TAZ sit and wait when the cell is not under enough tension to send them inside." },
  ["default fate"]: { term: "default fate", def: "The path a cell takes when nothing pushes it the other way, like the choice it falls into without a strong signal to switch it." },
  ["dermis"]: { term: "dermis", def: "The thicker inner layer of skin beneath the surface, made mostly of connective tissue and matrix that gives skin strength and structure." },
  ["dermo1"]: { term: "Dermo1", def: "A gene active in connective-tissue and bone-forming cells, used as a label to mark and study those cells in the developing face and skull." },
  ["developmental window"]: { term: "developmental window", def: "A limited stretch of time early in growth when a specific building step must happen; if it is missed or disrupted, the structure can form wrong." },
  ["dimensionality"]: { term: "dimensionality", def: "Whether cells are studied flat on a dish in 2D or surrounded by matrix in 3D, which matters because cells often behave differently in each setup." },
  ["distant spread"]: { term: "distant spread", def: "When cancer cells leave the original tumor and travel to set up new growths in far-off parts of the body." },
  ["e-cadherin (cdh1)"]: { term: "E-cadherin (CDH1)", def: "A sticky protein (made by the CDH1 gene) that glues epithelial cells tightly to their neighbors; losing it lets a cell break free and start moving." },
  ["ecm architecture"]: { term: "ECM architecture", def: "The layout of the extracellular matrix outside cells: how its fibers are arranged, aligned, and connected, which cells can read and respond to." },
  ["elastin"]: { term: "elastin", def: "A stretchy matrix protein that lets tissues like skin and blood vessels snap back to shape after being pulled or squeezed." },
  ["emt (epithelial-to-mesenchymal transition)"]: { term: "EMT (epithelial-to-mesenchymal transition)", def: "A switch where a settled, glued-together epithelial cell loosens its grip on neighbors and turns into a loose, crawling cell that can move and invade." },
  ["epithelial tissue"]: { term: "epithelial tissue", def: "A sheet of cells packed tightly together that lines surfaces and cavities in the body, like skin or the inside of an organ." },
  ["epithelial-to-mesenchymal transition"]: { term: "epithelial-to-mesenchymal transition", def: "A switch where a tightly attached sheet cell lets go of its neighbors and becomes a loose, mobile cell that can crawl and invade." },
  ["epithelial-to-mesenchymal transition (emt)"]: { term: "epithelial-to-mesenchymal transition (EMT)", def: "A switch (called EMT for short) where a tightly attached sheet cell releases its neighbors and becomes a loose, crawling cell that can move and invade." },
  ["epithelium"]: { term: "epithelium", def: "A tightly packed layer of cells that covers surfaces or lines spaces in the body, sitting on top of a basement membrane." },
  ["extracellular matrix (ecm)"]: { term: "extracellular matrix (ECM)", def: "The mesh of proteins and fibers outside cells (called the ECM) that cells grip, pull on, and read for cues about where to go and what to become." },
  ["facial prominences"]: { term: "facial prominences", def: "The separate lumps of tissue in the embryo's developing face that must grow toward each other and fuse; when fusion fails, a cleft lip or palate can result." },
  ["falsifiability"]: { term: "falsifiability", def: "The idea that a real scientific claim must be testable in a way that could prove it wrong, not just a statement nothing could ever disprove." },
  ["fgf"]: { term: "FGF", def: "A family of signaling proteins (fibroblast growth factors) that tell cells to grow, divide, or move during development of the face and skull." },
  ["fiber alignment"]: { term: "fiber alignment", def: "How lined-up or tangled the matrix fibers are; when fibers point the same way, they can act like tracks that guide cells in a direction." },
  ["fibril"]: { term: "fibril", def: "A thin thread-like strand that bundles with others to build larger matrix fibers, like a single string twisted into a thicker rope." },
  ["fibrillogenesis"]: { term: "fibrillogenesis", def: "The process of assembling matrix proteins into fibrils and fibers, basically how cells build the fiber framework of the matrix around them." },
  ["fibronectin (fn1)"]: { term: "fibronectin (FN1)", def: "A matrix protein (made by the FN1 gene) that forms the graded road neural crest cells grip and crawl along as they migrate to build the frontal bone." },
  ["fibronectin gradient"]: { term: "Fibronectin gradient", def: "A path where the protein fibronectin slowly gets thicker or thinner across the tissue, acting like a graded road that guides migrating cranial neural crest cells toward where they build the frontal bone." },
  ["fn1 turnover"]: { term: "FN1 turnover", def: "The ongoing cycle of cells laying down fresh fibronectin (the FN1 protein) and breaking down old fibronectin, which keeps the migration road updated as cells move and build." },
  ["follower cells"]: { term: "Follower cells", def: "Cells near the back of a moving group that travel behind the leader cells, taking the path the leaders open up rather than reading the road themselves." },
  ["force chain"]: { term: "Force chain", def: "A connected line of pulling and gripping that carries force from outside the cell to its nucleus: integrins grip the matrix, a focal adhesion forms, actomyosin pulls, and the tension reaches inside." },
  ["force gauge"]: { term: "Force gauge", def: "A tool that actually measures how hard something is pulling, in real force units, instead of just guessing tension from how the cell looks." },
  ["fret tension sensor"]: { term: "FRET tension sensor", def: "A high-end tool that lights up to report the real pulling force inside a single molecule; in this lab it is a locked rung, so its strong claims stay out of reach." },
  ["frontonasal prominence"]: { term: "Frontonasal prominence", def: "An early bump of tissue on the embryo's face that helps form the forehead, the bridge of the nose, and the middle of the upper lip." },
  ["fusion"]: { term: "Fusion", def: "When two separate flaps of growing face tissue meet and join smoothly into one piece; a cleft lip or palate happens when this joining fails." },
  ["genome"]: { term: "Genome", def: "The complete set of DNA instructions inside a cell, holding every gene the body could use to build and run itself." },
  ["geometric confinement"]: { term: "Geometric confinement", def: "Forcing a cell into a certain size or shape by limiting its space, which changes how spread out it is and can shift its fate decision." },
  ["germ layers"]: { term: "Germ layers", def: "The three basic sheets of cells in an early embryo (ectoderm, mesoderm, and endoderm) that each go on to build different parts of the body." },
  ["glycosaminoglycan"]: { term: "Glycosaminoglycan", def: "A long, sugary chain in the matrix outside cells that grabs water and helps give tissue its springy, cushiony feel." },
  ["gradient"]: { term: "Gradient", def: "A smooth change in the amount of something across space, like a signal that is strong on one side and slowly fades toward the other, which cells can read for direction." },
  ["healthy instruction"]: { term: "Healthy instruction", def: "A normal signal that tells a cell to do the right job at the right place, like build bone where bone belongs, the way development is supposed to work." },
  ["hijack"]: { term: "Hijack", def: "When a process meant for healthy building gets taken over and used for harm, such as a cancer cell stealing the same gripping and pulling system that normal cells use to develop." },
  ["honest ceiling"]: { term: "Honest ceiling", def: "The highest claim you are allowed to make, set by your most direct tool: you can only say as much as your measurement actually reached, no higher." },
  ["hyaluronan"]: { term: "Hyaluronan", def: "A large, water-loving molecule in the matrix outside cells that holds moisture and gives tissue a soft, slippery, cushioned quality." },
  ["independent data point"]: { term: "Independent data point", def: "One separate result that does not depend on the others, such as one embryo or one model run; counting many cells inside a single run as separate points is a mistake called pseudoreplication." },
  ["induction"]: { term: "Induction", def: "When one group of cells sends a signal that tells nearby cells what type to become, steering their fate during development." },
  ["interpreter"]: { term: "Interpreter", def: "Something inside the cell that reads an incoming signal and turns it into an action, like YAP and TAZ reading the cell's tension and switching genes on or off." },
  ["interstitial ecm"]: { term: "Interstitial ECM", def: "The loose, fibrous matrix filling the spaces between cells in a tissue, different from the thin sheet that lines surfaces." },
  ["invasion"]: { term: "Invasion", def: "When cancer cells push past their normal boundary and crawl into nearby tissue they should not be in, the opposite of staying put." },
  ["invasive front"]: { term: "Invasive front", def: "The leading edge of a tumor where its cells are actively breaking into healthy tissue, which tends to look more spatially disordered than matched normal tissue." },
  ["kinase"]: { term: "Kinase", def: "An enzyme that adds a small chemical tag (a phosphate) onto another protein to switch its activity on or off, a common way cells pass along signals." },
  ["laminin"]: { term: "Laminin", def: "A protein that is a main building block of the basement membrane, the thin sheet cells rest on and that cancer cells must breach to invade." },
  ["leader cells"]: { term: "Leader cells", def: "Cells at the front of a moving group that read the road outside, set the direction, and open the path for the follower cells behind them." },
  ["locked rung"]: { term: "Locked rung", def: "A high step on the measurement ladder that uses a tool this lab does not have (like FRET or AFM), so the strong claims it would allow stay out of reach." },
  ["lox (lysyl oxidase)"]: { term: "LOX (lysyl oxidase)", def: "An enzyme that ties matrix fibers together with crosslinks to make tissue stiffer; in the cancer act, the tumor uses LOX to stiffen its own surroundings." },
  ["lysyl oxidase (lox)"]: { term: "Lysyl oxidase (LOX)", def: "An enzyme that locks matrix fibers together with crosslinks to make tissue stiffer; in the cancer act, the tumor uses it to harden the matrix it crawls through." },
  ["master switch"]: { term: "Master switch", def: "A single control that flips a big decision for the cell, such as a gene that chooses whether the cell becomes bone or cartilage." },
  ["matched-niche stiffness"]: { term: "Matched-niche stiffness", def: "Setting your test surface to the same firmness a cell would feel in its real home tissue, so the experiment matches the body instead of an unnatural value." },
  ["matrix metalloproteinase"]: { term: "Matrix metalloproteinase", def: "An enzyme that cuts and clears the matrix outside cells, opening space so cells can move, remodel tissue, or invade." },
  ["matrix metalloproteinase (mmp)"]: { term: "Matrix metalloproteinase (MMP)", def: "An enzyme (short name MMP) that snips apart the matrix outside cells, clearing a path that lets cells migrate, rebuild tissue, or break in." },
  ["matrix remodeling"]: { term: "Matrix remodeling", def: "Cells reshaping the material around them by adding new fibers, cutting old ones, or stiffening it, which changes the road and the forces other cells feel." },
  ["matrix stiffness"]: { term: "Matrix stiffness", def: "How firm or soft the material outside a cell is; a cell pulls against it, and stiffer matrix sends more YAP and TAZ into the nucleus, pushing the fate decision toward bone." },
  ["maxillary process"]: { term: "Maxillary process", def: "A pair of growing face flaps on the embryo that build the sides of the upper jaw and upper lip and must fuse with the middle for the lip to close." },
  ["measurement ladder"]: { term: "Measurement ladder", def: "The five rungs of experiments in this lab, from cheap descriptive ones at the bottom up to a locked direct force measurement at the top, where each rung licenses only certain claims." },
  ["mechanical signaling"]: { term: "Mechanical signaling", def: "When physical force, not just chemicals, carries a message inside a cell: gripping and pulling on the matrix sends YAP and TAZ to the nucleus to change which genes turn on." },
  ["mechanosensing"]: { term: "Mechanosensing", def: "A cell's ability to feel physical forces and the stiffness of the matrix around it, then turn that feeling into a chemical signal that can change what the cell does." },
  ["medial edge epithelium (mee)"]: { term: "Medial edge epithelium (MEE)", def: "The thin layer of cells on the inner edges of the two palate shelves that must meet and disappear so the shelves can fuse into one roof of the mouth; when this fusion fails, a cleft palate can result." },
  ["medial nasal process"]: { term: "Medial nasal process", def: "A bump of growing tissue in the center of the developing face that helps form the middle of the upper lip and the front of the palate; if it does not join properly with neighboring tissue, a cleft lip can form." },
  ["mesenchymal stem cell"]: { term: "Mesenchymal stem cell", def: "An unspecialized cell that has not yet decided its job and can still become several connective tissue types, such as bone or cartilage, depending on the signals it gets." },
  ["microns"]: { term: "Microns", def: "A tiny unit of length equal to one millionth of a meter (a human hair is about 70 microns wide), used to measure cells and the spaces between them." },
  ["migration"]: { term: "Migration", def: "When cells crawl from one place to another in the body, like the neural crest cells that travel along a chemical road to reach the spot where they will build facial bone." },
  ["mmps (matrix metalloproteinases)"]: { term: "MMPs (matrix metalloproteinases)", def: "A family of enzymes that act like scissors to cut and break down the matrix outside cells, which can clear a path for cells to move through or, in cancer, help a tumor break out." },
  ["model basis"]: { term: "Model basis", def: "The set of facts and assumptions a model is built on, which tells you what the model can fairly be used to claim and where it stops being trustworthy." },
  ["molecular clutch"]: { term: "Molecular clutch", def: "The connection a cell uses to grip the matrix outside and link it to its inner motor, so that when the motor pulls, the grip holds and the cell can feel and use the force; when the grip slips, the force is lost, like a slipping clutch in a car." },
  ["mutant phenotype"]: { term: "Mutant phenotype", def: "The visible traits or behavior you see when a gene is changed or broken, compared to the normal version, which helps scientists figure out what that gene normally does." },
  ["myosin"]: { term: "Myosin", def: "A motor protein inside cells that grabs onto fiber tracks (actin) and pulls, generating the tension a cell needs to move, change shape, or squeeze its surroundings." },
  ["myosin ii"]: { term: "Myosin II", def: "A type of myosin motor that teams up with actin fibers to pull and create tension inside a cell, which is the force step that helps send YAP and TAZ into the nucleus." },
  ["myosin light chain kinase"]: { term: "Myosin light chain kinase", def: "An enzyme that switches the myosin motor on by adding a chemical tag (a phosphate) to it, turning up the pulling force a cell produces." },
  ["nearest-neighbor spacing"]: { term: "Nearest-neighbor spacing", def: "The distance from each cell to the closest cell next to it, measured to check whether cells are spread out evenly instead of clumping together randomly." },
  ["neural crest"]: { term: "Neural crest", def: "A special group of early cells that break away and crawl to many parts of the body; in the head they travel to build much of the face and skull, including the frontal bone in this sim." },
  ["neural folds"]: { term: "Neural folds", def: "The two raised ridges of an early embryo that rise up and curl toward each other so they can meet and zip closed into the tube that becomes the brain and spinal cord." },
  ["neural plate"]: { term: "Neural plate", def: "A flat sheet of early cells in an embryo that later folds up and closes into the tube that forms the brain and spinal cord." },
  ["neural plate border"]: { term: "Neural plate border", def: "The edge zone around the flat neural plate where the neural crest cells are born before they break away and migrate to build parts of the face and body." },
  ["neurulation"]: { term: "Neurulation", def: "The early step in which the flat neural plate folds up and closes into a tube, forming the start of the brain and spinal cord." },
  ["non-muscle myosin ii"]: { term: "Non-muscle myosin II", def: "The version of the myosin II motor found in ordinary cells (not muscle cells) that pulls on actin fibers to create the tension a cell uses to move and change shape." },
  ["non-random spacing"]: { term: "Non-random spacing", def: "When cells are spread out in an orderly, evenly spaced pattern rather than scattered by chance, which is a sign the cells are actively organizing themselves." },
  ["normalization"]: { term: "Normalization", def: "Adjusting measurements to a common baseline so different samples can be compared fairly, like putting all results on the same scale before you judge them." },
  ["nuclear deformation"]: { term: "Nuclear deformation", def: "A change in the shape of a cell's nucleus caused by physical pulling or pressure, which can affect which genes get turned on or off." },
  ["nuclear translocation"]: { term: "Nuclear translocation", def: "When a signaling protein moves from the main body of the cell into the nucleus, like YAP and TAZ entering the nucleus to switch a gene decision on." },
  ["off-switch"]: { term: "Off-switch", def: "Something that turns a signal or process off, such as a step that keeps YAP and TAZ out of the nucleus so a gene stays quiet." },
  ["one toolkit, opposite readings"]: { term: "One toolkit, opposite readings", def: "The idea that the same cellular machinery (grip, tension, YAP and TAZ) can be read in opposite ways: it can build healthy tissue or, when hijacked, help a cancer invade." },
  ["operator"]: { term: "Operator", def: "A control switch on DNA where a protein can attach to turn a gene on or off, acting like a gate that decides whether the gene is read." },
  ["over-claim"]: { term: "Over-claim", def: "Saying your results prove more than your tools actually measured, like claiming tension caused something when you only measured spacing; honest science avoids this." },
  ["overclaim"]: { term: "Overclaim", def: "Stating that your data shows more than it really does, for example claiming a cause when you only measured a pattern; honest science stays inside what the tools actually reached." },
  ["pharyngeal arches"]: { term: "Pharyngeal arches", def: "A series of tissue bands in the neck and throat region of an early embryo that grow and reshape into parts of the face, jaw, and neck." },
  ["phospho-myosin light chain"]: { term: "Phospho-myosin light chain", def: "The active, switched-on form of the myosin motor after a phosphate tag has been added to it, which is a sign the cell is actively producing pulling force." },
  ["phospho-myosin light chain (phospho-mlc)"]: { term: "Phospho-myosin light chain (phospho-MLC)", def: "The active form of the myosin motor that carries an added phosphate tag, used as a readout that a cell is generating tension." },
  ["phosphorylation"]: { term: "Phosphorylation", def: "Adding a small phosphate tag to a protein, which often works like flipping a switch to turn that protein's activity on or off." },
  ["planar cell polarity"]: { term: "Planar cell polarity", def: "The way a sheet of cells lines up in the same direction across a tissue, like fish all facing one way, so they can move or build structures in a coordinated pattern." },
  ["pore size"]: { term: "Pore size", def: "How big the open gaps are in the mesh of matrix outside cells, which decides how easily a cell can squeeze through or how stiff the material feels." },
  ["positional signal"]: { term: "Positional signal", def: "A chemical cue that tells a cell where it is in the body, like a road sign, so it knows where to go or what to become." },
  ["positive control"]: { term: "Positive control", def: "A test set up to give a known, expected result, used to prove your experiment is working before you trust your real measurements." },
  ["protease"]: { term: "Protease", def: "An enzyme that cuts proteins into smaller pieces, which cells use to remodel the matrix around them or to clear a path to move." },
  ["proteoglycan"]: { term: "Proteoglycan", def: "A protein coated with sugar chains that sits in the matrix outside cells, holding water and giving tissue its cushiony, gel-like support." },
  ["qualitative scale"]: { term: "Qualitative scale", def: "A way of rating something by category or rank (like low, medium, high) instead of an exact number, so it tells you the general direction but not the precise amount." },
  ["rate-limiting step"]: { term: "Rate-limiting step", def: "The slowest step in a chain of events, which sets how fast the whole process can go, like the slowest checkout lane setting how fast a store line moves." },
  ["remodeling"]: { term: "Remodeling", def: "When cells rebuild or rearrange the material around them, adding, trimming, or reorganizing the matrix so the tissue takes on a new shape or stiffness." },
  ["replicate (n)"]: { term: "Replicate (n)", def: "One independent repeat of the whole experiment, and the number of these repeats (called n) is your real sample size, not the number of cells inside each one." },
  ["reuse not reversal"]: { term: "Reuse, not reversal", def: "The idea that the cancer in the sim hijacks the same normal toolkit (gripping, pulling, sensing stiffness) and uses it for invasion, rather than running the normal process backwards." },
  ["rgd motif"]: { term: "RGD motif", def: "A short three-letter tag (arginine-glycine-aspartate) in matrix proteins like fibronectin that a cell's integrins grab onto, like a handle the cell can grip." },
  ["scientific debate"]: { term: "Scientific debate", def: "When scientists openly disagree about what the evidence means and argue it out with data, which is a normal and healthy part of how science gets more accurate." },
  ["sdf1/cxcr4"]: { term: "Sdf1 / Cxcr4", def: "A signal-and-receiver pair, where Sdf1 is a chemical trail and Cxcr4 is the matching receiver on a cell, helping migrating cells follow a path to the right place." },
  ["sibling sample"]: { term: "Sibling sample", def: "In the sim, a tissue sample taken from a related source (a sibling) so its tumor can be compared fairly against matched normal tissue from the same background." },
  ["snail"]: { term: "Snail", def: "A gene that, when switched on, tells a cell to loosen its connections to neighbors and become more mobile, a change cancer cells use to start invading." },
  ["spatial disorder"]: { term: "Spatial disorder", def: "When cells or structures are arranged in a messy, irregular pattern instead of neat and evenly spaced, which the sim sees more of at the invasive edge of a tumor." },
  ["spatial organization is not the same thing as tension"]: { term: "Spacing is not tension", def: "A reminder that how cells are arranged in space (geometry) is a different thing from how hard they are pulling (force), so you cannot prove one by measuring the other." },
  ["spatial organization versus tension"]: { term: "Spacing vs. tension", def: "The contrast between cell spacing, which is about geometry and arrangement, and tension, which is about pulling force, two separate things that should not be confused." },
  ["specifier genes"]: { term: "Specifier genes", def: "Genes that lock in what kind of cell a cell will become, like the genes that mark a cell as a future neural crest cell." },
  ["statistical significance"]: { term: "Statistical significance", def: "A result big enough that plain luck is an unlikely explanation, usually meaning the chance of it happening by accident (the p-value) is below about 5 percent." },
  ["stiffness"]: { term: "Stiffness", def: "How hard or rigid a material is, meaning how much it resists being pushed or stretched, which cells can feel and respond to." },
  ["stiffness gradient"]: { term: "Stiffness gradient", def: "A gradual change in how stiff the surroundings are from one place to another, like soft on one side getting firmer toward the other, which some cells crawl along." },
  ["streams"]: { term: "Streams", def: "Organized streams of migrating cells that travel together along set paths, such as cranial neural crest cells flowing toward where they will build facial structures." },
  ["talin"]: { term: "Talin", def: "A protein inside the cell that links a gripping integrin to the cell's internal skeleton, acting as part of the chain that lets the cell pull on the matrix." },
  ["target gene"]: { term: "Target gene", def: "A gene that a signal turns on or off, so it is the gene at the end of the chain that actually gets switched as a result of the cell receiving the message." },
  ["tgf-beta3"]: { term: "TGF-beta3", def: "A signaling protein important for the facial prominences fusing together properly, and when it is missing, fusion can fail, as in some cleft palate cases." },
  ["time series"]: { term: "Time series", def: "A set of measurements taken of the same thing at many points in time, so you can see how it changes as time goes on." },
  ["timp"]: { term: "TIMP", def: "A protein that puts the brakes on matrix-cutting enzymes, keeping the breakdown of the material around cells under control instead of running unchecked." },
  ["traction"]: { term: "Traction", def: "The grip and pull a cell uses against the matrix outside it, the same way your shoe grips the ground so you can push off and move." },
  ["traction force"]: { term: "Traction force", def: "The actual amount of pulling force a cell applies to the material it is gripping, measured to tell how hard the cell is tugging." },
  ["transcriptional co-activator"]: { term: "Transcriptional co-activator", def: "A helper protein that does not bind DNA itself but teams up with gene-switching proteins to turn genes on, like YAP and TAZ do in the nucleus." },
  ["transglutaminase"]: { term: "Transglutaminase", def: "An enzyme that ties proteins together with strong cross-links, which can stiffen the material around cells by locking its strands in place." },
  ["transmembrane protein"]: { term: "Transmembrane protein", def: "A protein that passes all the way through the cell's outer membrane, so one end senses the outside while the other end works inside, like integrins do." },
  ["tumor margin"]: { term: "Tumor margin", def: "The edge of a tumor where it meets normal tissue, and in the sim this invasive margin is more spatially disordered than matched healthy tissue." },
  ["twist1"]: { term: "Twist1", def: "A gene that switches on programs making cells more mobile and able to move, which is used in normal development and also hijacked by invading cancer cells." },
  ["twist2 (dermo1)"]: { term: "Twist2 (Dermo1)", def: "A gene (also called Dermo1) that helps guide cells toward connective tissue and bone fates and influences how cells move and reshape tissue." },
  ["type iv collagen"]: { term: "Type IV collagen", def: "A special collagen that forms a sheet-like layer called the basement membrane, the barrier that invading cancer cells must breach to spread." },
  ["valid claim"]: { term: "Valid claim", def: "A conclusion you are allowed to make because your most direct measurement tool actually reached that high, so the data truly backs it up." },
  ["vinculin"]: { term: "Vinculin", def: "A protein that strengthens the cell's grip site, helping reinforce the connection between the gripping machinery and the cell's internal skeleton when force builds up." },
  ["voronoi diagram"]: { term: "Voronoi diagram", def: "A map that gives each cell the territory closest to it, used to measure how cells are spaced out by drawing a region around every cell." },
  ["yap/taz"]: { term: "YAP / TAZ", def: "A pair of helper proteins that move into the nucleus when a cell pulls hard on a stiff matrix, where they switch on genes that decide the cell's fate." },
  ["zygote"]: { term: "Zygote", def: "The single cell formed when an egg and sperm join, which is the very first cell that an entire organism grows from." },
}

/** Look up a term (case-insensitive). Returns null if not defined. */
export function lookup(term: string): GlossEntry | null {
  return GLOSSARY[term.toLowerCase().trim()] ?? null
}
